spring:
  application:
    name: ticket-payment
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
